verbose: false
instrumentation:
    default-excludes: true
    excludes: ['**/test.js', '**/*.test.js', '**/build/**']
    include-all-sources: true
reporting:
    print: summary
    reports:
        - html
